# fly.toml app configuration file generated for apijuanmcell on 2023-05-25T12:40:57-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "apijuanmcell"
primary_region = "bog"

[http_service]
  internal_port = 9001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
